services:
  kagami:
    env_file: .env
    image: nova8x/kagami_bot:amd64
    container_name: kagami_bot
    network_mode: host
#    user: 1000:1000
    volumes:
#      - ${DATA_PATH}:/kagami/data
      - ./kagami/data:/kagami/data
    expose:
      - 8077
    ports:
      - 8077:8077
    restart: "unless-stopped"
  lavalink:
    env_file: .env
    # pin the image version to Lavalink v3.7.8
    image: ghcr.io/lavalink-devs/lavalink:4.1.1
    container_name: lavalink
    restart: 'unless-stopped'
    user: "322:322"
    environment:
      # set Java options here
      - _JAVA_OPTIONS=-Xmx1G
      # set lavalink server port
      - SERVER_PORT=2333
      # set password for lavalink
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
    volumes:
      # mount application.yml from the same directory or use environment variables
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    network_mode: host
    expose:
      # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
      - 2333
    ports:
      # you only need this if you want to make your lavalink accessible from outside of containers
      - "2333:2333"
